### ISSUE TITLE
[ROADMAP] Update to 1.14

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#1242]
- [x] Make it compile with 1.14
- [x] Check all pet types to function correctly
- [x] Update all pet data from 1.13.2 to 1.14 correctly when pet gets loaded
  - [x] villagers
  - [x] zombie villagers
  - [x] cats/ocelots
- [x] Add 1.14 items to item DB
- [x] Add new 1.14 Mobs
  - [x] brown Mooshroom
  - [x] cats
  - [x] foxes
  - [x] pandas
  - [x] pillagers
  - [x] ravagers
  - [x] wandering traders
  - [x] trader llama
- [x] add new mobs to SkilltreeCreator
